# Generated by Django 4.2.8 on 2024-06-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_history", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
