version: '3.8'

services:
  production:
    profiles: [production]
    image: eugeniusms/patera:latest
    container_name: patera
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "80:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=app.patera.settings